/**
 * Agent Chat Engine
 * Conversational AI portfolio manager. Replies are generated by Claude via the
 * `/api/chat` route; relevant one-click actions (analyze / rebalance / pay) are
 * attached with lightweight intent detection. If the AI call fails, a
 * rule-based fallback keeps the agent responsive.
 */

import { Portfolio, AIAnalysis } from './casper'

export interface ChatMessage {
  id: string
  role: 'user' | 'agent'
  content: string
  timestamp: Date
  actions?: AgentAction[]
}

export interface AgentAction {
  type: 'analyze' | 'rebalance' | 'pay' | 'explore'
  label: string
  payload?: unknown
}

/** Suggest one-click actions based on the user's intent and current state. */
const suggestActions = (
  userMessage: string,
  portfolio: Portfolio | null,
  analysis: AIAnalysis | null
): AgentAction[] => {
  const msg = userMessage.toLowerCase()

  if (/rebalanc|allocat|adjust/.test(msg)) {
    return [
      { type: 'rebalance', label: 'View Rebalancing Plan' },
      { type: 'analyze', label: 'Generate New Plan' },
    ]
  }
  if (/pay|cost|fee|x402/.test(msg)) {
    return [{ type: 'pay', label: 'Pay for Analysis (0.01 CSPR)' }]
  }
  if (/risk|analyz|portfolio|holding/.test(msg)) {
    return portfolio
      ? [
          { type: 'analyze', label: 'Run Full AI Analysis' },
          { type: 'explore', label: 'View Asset Breakdown' },
        ]
      : []
  }
  return portfolio && !analysis
    ? [{ type: 'analyze', label: 'Full Analysis' }]
    : []
}

const ruleBasedReply = (
  userMessage: string,
  portfolio: Portfolio | null,
  analysis: AIAnalysis | null
): string => {
  const msg = userMessage.toLowerCase()
  if (/risk/.test(msg) && analysis?.riskAssessment) {
    return `**Risk Assessment:** ${analysis.riskAssessment}`
  }
  if (/rebalanc/.test(msg) && analysis?.rebalancingSuggestion) {
    return `**Rebalancing:** ${analysis.rebalancingSuggestion.action}\n\n${analysis.rebalancingSuggestion.reasoning}`
  }
  if (/pay|cost|fee|x402/.test(msg)) {
    return 'Each AI analysis costs **0.01 CSPR** via the x402 micropayment protocol, settled on-chain so the agent can operate autonomously.'
  }
  if (portfolio) {
    return `Your portfolio is worth **$${portfolio.totalValue.toFixed(2)}** across ${portfolio.assets.length} assets, led by ${portfolio.assets[0]?.symbol} at ${portfolio.assets[0]?.percentage.toFixed(1)}%. Want a full AI analysis?`
  }
  return "I'm your Casper AI Portfolio Agent! Connect a wallet and I can analyze your holdings, assess risk, and suggest rebalancing. 🐻"
}

/**
 * Generate an agent response. Calls Claude through the `/api/chat` route and
 * falls back to a rule-based reply on error so the UI never stalls.
 */
export const generateAgentResponse = async (
  userMessage: string,
  portfolio: Portfolio | null,
  analysis: AIAnalysis | null
): Promise<{ message: string; actions: AgentAction[] }> => {
  const actions = suggestActions(userMessage, portfolio, analysis)

  try {
    const res = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: userMessage, portfolio, analysis }),
    })

    if (res.ok) {
      const data = await res.json()
      if (data?.message) {
        return { message: data.message, actions }
      }
    }
  } catch {
    // fall through to rule-based reply
  }

  return { message: ruleBasedReply(userMessage, portfolio, analysis), actions }
}
