'use client'

import { useState, useRef, useEffect } from 'react'
import { Portfolio } from '@/lib/casper'
import { generateAgentResponse, ChatMessage, AgentAction } from '@/lib/agent-chat'
import { createX402Payment, ANALYSIS_COST_CSPR, ANALYSIS_RECIPIENT } from '@/lib/x402'
import { Send, Bot, User, Sparkles, Zap, Heart, Wallet } from 'lucide-react'

interface AgentChatProps {
  portfolio: Portfolio | null
  analysis: any | null
  onAnalyze: () => void
}

export const AgentChat = ({ portfolio, analysis, onAnalyze }: AgentChatProps) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'agent',
      content: 'Hello! I\'m your Casper AI Portfolio Agent 🐻✨ I can analyze your portfolio, assess risk, suggest rebalancing, and even pay for analysis via x402 micropayments. How can I help you today?',
      timestamp: new Date(),
      actions: [
        { type: 'analyze', label: 'Analyze Portfolio' },
        { type: 'explore', label: 'Learn About x402' }
      ]
    }
  ])
  const [input, setInput] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSend = async () => {
    if (!input.trim()) return

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date()
    }

    setMessages(prev => [...prev, userMsg])
    setInput('')
    setIsTyping(true)

    // Simulate agent thinking
    await new Promise(resolve => setTimeout(resolve, 800))

    const response = await generateAgentResponse(input, portfolio, analysis)

    const agentMsg: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: 'agent',
      content: response.message,
      timestamp: new Date(),
      actions: response.actions
    }

    setMessages(prev => [...prev, agentMsg])
    setIsTyping(false)
  }

  const handleAction = async (action: AgentAction) => {
    if (action.type === 'analyze') {
      onAnalyze()
      return
    }

    if (action.type === 'pay') {
      setIsTyping(true)
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      // Simulate x402 payment
      const payment = await createX402Payment(ANALYSIS_COST_CSPR, ANALYSIS_RECIPIENT, 'Portfolio AI Analysis')
      
      const paymentMsg: ChatMessage = {
        id: (Date.now() + 2).toString(),
        role: 'agent',
        content: `✅ **x402 Payment Processed**\n\n- Amount: ${payment.amount} CSPR\n- Token: ${payment.token}\n- Purpose: ${payment.purpose}\n- Status: Confirmed on Casper Testnet\n\nYour analysis is now being generated by Claude AI...`,
        timestamp: new Date(),
        actions: [{ type: 'analyze', label: 'View Analysis Results' }]
      }

      setMessages(prev => [...prev, paymentMsg])
      setIsTyping(false)
      
      // Trigger actual analysis after payment
      setTimeout(() => onAnalyze(), 1500)
      return
    }

    // Handle explore and other actions
    const response = await generateAgentResponse(action.label, portfolio, analysis)
    const exploreMsg: ChatMessage = {
      id: (Date.now() + 3).toString(),
      role: 'agent',
      content: response.message,
      timestamp: new Date(),
      actions: response.actions
    }
    setMessages(prev => [...prev, exploreMsg])
  }

  return (
    <div className="bg-white border-2 border-gray-100 rounded-3xl shadow-xl overflow-hidden flex flex-col h-[500px]">
      {/* Header */}
      <div className="px-6 py-4 bg-gradient-to-r from-primary to-secondary border-b border-gray-100">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-white/20 flex items-center justify-center backdrop-blur-sm">
            <Bot className="w-5 h-5 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-white">Casper AI Agent</h3>
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
              <span className="text-xs text-white/80 font-semibold">Online • x402 Enabled</span>
            </div>
          </div>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
            <div className={`w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0 ${
              msg.role === 'agent' 
                ? 'bg-gradient-to-br from-primary to-secondary' 
                : 'bg-gray-100'
            }`}>
              {msg.role === 'agent' ? (
                <Bot className="w-4 h-4 text-white" />
              ) : (
                <User className="w-4 h-4 text-gray-600" />
              )}
            </div>
            
            <div className={`max-w-[80%] space-y-2 ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              <div className={`px-4 py-3 rounded-2xl ${
                msg.role === 'agent'
                  ? 'bg-gray-50 text-gray-800 rounded-tl-sm'
                  : 'bg-gradient-to-r from-primary to-secondary text-white rounded-tr-sm'
              }`}>
                <p className="text-sm whitespace-pre-line font-medium">{msg.content}</p>
              </div>
              
              {msg.actions && msg.actions.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {msg.actions.map((action, idx) => (
                    <button
                      key={idx}
                      onClick={() => handleAction(action)}
                      className="px-3 py-1.5 bg-white border-2 border-primary/20 rounded-xl text-xs font-bold text-primary hover:bg-primary hover:text-white transition-all transform hover:scale-105 flex items-center gap-1"
                    >
                      {action.type === 'analyze' && <Sparkles className="w-3 h-3" />}
                      {action.type === 'pay' && <Zap className="w-3 h-3" />}
                      {action.type === 'rebalance' && <Wallet className="w-3 h-3" />}
                      {action.type === 'explore' && <Heart className="w-3 h-3" />}
                      {action.label}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}
        
        {isTyping && (
          <div className="flex gap-3">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
              <Bot className="w-4 h-4 text-white" />
            </div>
            <div className="bg-gray-50 px-4 py-3 rounded-2xl rounded-tl-sm">
              <div className="flex gap-1">
                <div className="w-2 h-2 rounded-full bg-primary animate-bounce" />
                <div className="w-2 h-2 rounded-full bg-secondary animate-bounce" style={{ animationDelay: '0.2s' }} />
                <div className="w-2 h-2 rounded-full bg-cute-dark animate-bounce" style={{ animationDelay: '0.4s' }} />
              </div>
            </div>
          </div>
        )}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-100 bg-white">
        <div className="flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Ask your agent anything..."
            className="flex-1 px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-2xl text-sm text-black placeholder-gray-400 focus:outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all"
          />
          <button
            onClick={handleSend}
            className="px-4 py-3 bg-gradient-to-r from-primary to-secondary text-white rounded-2xl hover:shadow-lg transition-all transform hover:scale-105"
          >
            <Send className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  )
}
